[project]
name = "picostatus"
version = "0.1.0"
description = "Little toy status for RPI Pico 2 and SSD1305 display"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "adafruit-circuitpython-displayio-ssd1305",
  "adafruit-circuitpython-display-text",
  "adafruit-blinka",
  "circuitpython-stubs",
  "pyserial",
  "python-mpd2",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = ["CPY"]


